services:
  mongodb:
    image: "mongo:8.0-rc-jammy"
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_ROOT_USERNAME: test
    ports:
      - "27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://test:test@mongodb:27017/
      ME_CONFIG_BASICAUTH: false