apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongodb
spec:
    serviceName: kyosk-mongodb
    selector:
        matchLabels:
            app: mongodb
    replicas: 1
    template:
        metadata:
            labels:
                app: mongodb
        spec:
            containers:
                - name: mongodb
                  image: mongo:8.0-rc-jammy
                  volumeMounts:
                      - name: mongo-persistent-storage
                        mountPath: /data/db
            volumes:
                - name: mongo-persistent-storage
                  persistentVolumeClaim:
                      claimName: kyosk-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: kyosk-mongodb
spec:
    type: ClusterIP
    selector:
        app: mongodb
    ports:
        - name: mongoport
          port: 27017
