apiVersion: v1
kind: PersistentVolumeClaim # specifies "What do we want?"
metadata:
    name: kyosk-mongo-pvc
spec:
    storageClassName: kyosk-local-storage # bind PVC with PV
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume # specifies "How do we want it implemented?"
metadata:
    name: local-storage
spec:
    storageClassName: kyosk-local-storage
    accessModes:
        - ReadWriteOnce
    capacity: # not useful for a hostPath
        storage: 1Gi
    hostPath:
        path: "/mnt/kyosk-mongo/"
