apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/ajharry69/kyosk-test:v1.0.0
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: "kyosk-mongodb.default.svc.cluster.local"